:toc:
:toc-placement!:

This Asciidoc file is where you will place your answers to written questions for practical 6. An AsciiDoc is a plain text markup language that is like markdown, however the output of Asciidoc is standardised unlike markdown. If you open this file in GitHub you will see it has been beautified into an HTML output. Make sure you delete filler text.

toc::[]

== Question 1: ADCs
What type of ADC does the STM32F051x6 have? How does it operate, i.e. how does it convert an integer value from an analog voltage?

[NOTE]
====
The STM32F051x6 microcontroller uses a 12-bit Successive Approximation Register (SAR) ADC to convert analog voltages into digital values.
It operates by sampling the input voltage and using a binary search algorithm to compare it against reference voltages generated internally by a DAC.
Starting from the most significant bit, the ADC determines each bit based on whether the input is higher or lower than the current approximation.
====

*Maximum Score = 3*

== Question 2: Calibration
Write down two lines of code that are used to calibrate the ADC?

[,C]
----
ADC1->CR |= ADC_CR_ADCAL;                  // Start calibration
while (ADC1->CR & ADC_CR_ADCAL !=0);           // Wait until calibration is complete
----

*Maximum Score = 2*

== Question 3: Memory
What is the endianness of a word stored in the memory of an STM32F0x1 microcontroller? What does this mean?

[NOTE]

====
The STM32F0x1 microcontroller uses little-endian format to store data in memory. 
This means that the least significant byte is stored at the lowest memory address, and the most significant byte
is stored at the highest address. 
====

*Maximum Score = 2*

== Question 4: Priority
The NVIC has priorities for all the possible interrupts on the SMT32Fx1. Which of the following has the greater priority: `EXTI0_1` or `TIM_2`?

[NOTE]
====
EXTI0_1 has higher priority
====

*Maximum Score = 1*

== Question 5: Timing
What is a racing condition and why are they undesirable?

[NOTE]
====
A race condition happens when two or more parts of a program access shared data at the same time, and the final result depends on which program finishes first.
A race condition is undesirable because it can lead to unpredictable and incorrect program behavior, such as corrupted data, or missed events.
Since the outcome depends on timing, it can be hard to detect, debug the code.
====

*Maximum Score = 2*

== Question 6: Memory Part 2 
What is DMA and why is it useful?

[NOTE]
====
DMA (Direct Memory Access) is a feature that allows peripherals to transfer
data directly to or from memory without CPU involvement. It is useful
because it frees up the CPU to perform other tasks, improves performance, and enables faster data transfers.
====
*Maximum Score = 1*

